### ISSUE TITLE
Incomplete `.ts` file in `translations` folder

### ISSUE THREAD

**Issue by TylerTemp** [mMjMm/upANDdown#1]
Many strings in app are missed in the `translations/upanddown.ts` file, which makes the translation job impossible.

Could you please fix it? Thx :-)

**Comment by mMjMm** [comment]
hey tylerTemp,

to be honest... upanddown is my first app ever and and for me some sort of learning by doing. So thank you for pointing me to the issue with the translation .ts file and i will figure it out. (but please give me some time... i have absolute no idea how a perfect .ts file has to look like.)

cheers mjm

**Comment by mMjMm** [comment]
okay think i got it... qsTr should do the the job?
Text {
    id: txt1;
    text: qsTr("Back");
}
http://doc.qt.io/qt-5/qtquick-internationalization.html
lg mjm

**Comment by TylerTemp** [comment]
I'm not a C++ programmer so I can't commit a request to help :(

Maybe you can have a look at the source code of [SailfishWlanKeyboard](https://github.com/abertschi/sailfish-wlan-keyboard) ?

Anyway,  Thx for your work :-)

**Comment by mMjMm** [comment]
updated all strings with the appropriate qsTr(). First translation in swedish is ready. Thanks to  [eson57](https://github.com/eson57)
