### ISSUE TITLE
Translation strings not working

### ISSUE THREAD

**Issue by eson57** [mMjMm/upANDdown#4]
Hi,
There's two strings that don't translate into Swedish.
Line 156 and line 162.

![screenshot-16-03-13-06-09-47](https://cloud.githubusercontent.com/assets/2996154/13727078/0d150786-e8e4-11e5-867c-da2ac6bea364.png)

**Comment by mMjMm** [comment]
hello, thank you for pointing me to that mistake!
fixed it!
(harbour version is without haptic feedback and the *.ts is automatically generated and so i messed it up ... ;-) )

**Comment by eson57** [comment]
ok, thanks for the new version btw...
